### ISSUE TITLE
Circle CI error

### ISSUE THREAD

**Issue by agungyuliaji** [lmaccherone/node-localstorage#37]
```
$ NODE_ENV=test mocha-webpack --reporter mocha-junit-reporter
/home/circleci/<project-name>/node_modules/node-localstorage/LocalStorage.js:160
            throw e;
            ^

Error: ENOENT: no such file or directory, mkdir '/home/circleci/<project-name>/build/localStorageTemp'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at LocalStorage._init (/home/circleci/<project-name>/node_modules/node-localstorage/LocalStorage.js:156:14)
    at new LocalStorage (/home/circleci/<project-name>/node_modules/node-localstorage/LocalStorage.js:121:12)
    at Object.<anonymous> (/home/circleci/<project-name>/test/helpers/browser.js:13:23)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

😁

**Comment by agungyuliaji** [comment]
fixed by manually create `localStorageTemp` 😄

**Comment by lmaccherone** [comment]
Glad you figured it out. :-)
